services:
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=mysecretkey
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_FIRST_NAME=Admin
      - ADMIN_LAST_NAME=User
      - ADMIN_EMAIL=admin@superset.com
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    restart: unless-stopped
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username \$${ADMIN_USERNAME} --firstname \$${ADMIN_FIRST_NAME} --lastname \$${ADMIN_LAST_NAME} --email \$${ADMIN_EMAIL} --password \$${ADMIN_PASSWORD} &&
      superset init &&
      superset load_examples &&
      superset run -h 0.0.0.0 -p 8088"
  
volumes:
  superset_home: