services:
  - type: web
    name: superset
    env: docker
    plan: free
    envVars:
      - key: SUPERSET_SECRET_KEY
        value: mysecretkey
    dockerfilePath: ./Dockerfile
    autoDeploy: true